// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://avnebtibuclkuqjmzhce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2bmVidGlidWNsa3Vxam16aGNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwODYzMjksImV4cCI6MjA1NDY2MjMyOX0.aaS4wCCap-Vbv3hw6Br-a5nECtqEtHBH2RCTGsl6Dj8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);